name = "IndexedFactorGraphs"
uuid = "edf0a622-c16b-410a-a162-e53dc16a76ae"
authors = ["stecrotti <stefano.crotti@polito.it>"]
version = "0.1.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IndexedGraphs = "8a731c18-cfb7-4915-927e-cc26b56b67cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
IndexedFactorGraphsPlotsExt = ["Plots", "GraphRecipes"]

[compat]
FillArrays = "1.7"
GraphRecipes = "0.5"
Graphs = "1.9, 1.10"
IndexedGraphs = "0.6"
Plots = "1.39"
Random = "1.9, 1.10"
SparseArrays = "1.9, 1.10"
StatsBase = "0.34"
julia = "1.9, 1.10"